pugs ::
	ghc ./dist/build/pugs/pugs-tmp/cbits/*o -package mtl-1.1.1.1 -idist/build/autogen -isrc --make src/Main.hs 
	mv src/Main pugs

ghci ::
	ghci ./dist/build/pugs/pugs-tmp/cbits/*o -package mtl-1.1.1.1 -idist/build/autogen -isrc src/Main.hs 
